#!/usr/bin/env python
"""Is interface buffering caused by the partner, or by the positions themselves?

The problem this settles
------------------------
Script 04 finds that interface positions absorb less of an imposed charge bias
than bulk surface positions, and script 07 shows that survives matching on
relative solvent accessibility. Neither establishes *why*. Matching on burial
removes the most obvious confound, but "interface" positions could still differ
from matched surface positions in some way the matching does not capture:
secondary structure, local contact number, native residue identity, position
along the chain.

If the effect is really about the interface, it must depend on ProteinMPNN
being able to see the partner. The model has no notion of "interface" except
through partner context, so removing the partner from its input should remove
the effect. If buffering survives with no partner present, it was never an
interface effect and the label is wrong.

The design
----------
Two arms over the same complexes, the same beta grid and the same derived seeds:

``paired``
    ProteinMPNN sees the whole complex, as in the main analysis.
``isolated``
    The partner chain is removed from the structure entirely before the model
    sees it, so the designed chain is scored with no partner context at all.

Interface membership is defined on the **native complex** in both arms, so the
two are compared over an identical set of positions. Only the model's knowledge
differs.

Both arms are generated by ``scripts/10_regenerate_designs.py``, the second with
``--isolated-chain``, and each is then run through scripts 01, 02 and 04. This
script consumes the two per-complex tables and reports the paired difference.

Reading the result
------------------
The statistic is a difference of differences. Within each arm, take
``interface buffering ratio minus surface buffering ratio``: negative means the
interface absorbs less, which is buffering. Then compare that gap between arms,
paired by complex.

A positive effect of removing the partner means buffering weakened without it,
which is the causal claim. An effect indistinguishable from zero means the
partner was never doing the work.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

import pandas as pd

from interface_charge.cli import add_common_arguments, banner, fail, resolve_config
from interface_charge.config import RESULTS_DIR
from interface_charge.provenance import manifest_path_for, run_manifest
from interface_charge.statistics import bootstrap_ci, paired_bootstrap_ci


def buffering_gap(path: Path) -> pd.Series:
    """Interface minus surface buffering ratio, one value per complex.

    Negative is buffering: the interface takes up less of the imposed charge
    than bulk surface does, relative to how many residues each region has.
    """
    table = pd.read_csv(path)
    missing = {"pdb_id", "partition", "buffering_ratio"} - set(table.columns)
    if missing:
        raise KeyError(f"{path} is missing column(s) {sorted(missing)}")
    wide = table.pivot_table(index="pdb_id", columns="partition", values="buffering_ratio")
    for needed in ("interface", "surface"):
        if needed not in wide.columns:
            raise KeyError(f"{path} has no '{needed}' partition")
    return (wide["interface"] - wide["surface"]).dropna()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--paired",
        type=Path,
        default=Path("results/ablation_paired/analysis_per_complex.csv"),
        help="Per-complex table from the arm where ProteinMPNN saw the partner.",
    )
    parser.add_argument(
        "--isolated",
        type=Path,
        default=Path("results/ablation_isolated/analysis_per_complex.csv"),
        help="Per-complex table from the arm where the partner was removed.",
    )
    parser.add_argument("--seed", type=int, default=0)
    return add_common_arguments(parser)


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    resolve_config(args)
    results_dir = args.results_dir or RESULTS_DIR
    results_dir.mkdir(parents=True, exist_ok=True)

    for path in (args.paired, args.isolated):
        if not path.is_file():
            fail(
                f"{path} not found. Generate both arms first:\n"
                "  scripts/10_regenerate_designs.py ... --out-dir data/ablation/paired\n"
                "  scripts/10_regenerate_designs.py ... --isolated-chain "
                "--out-dir data/ablation/isolated\n"
                "then run scripts 01, 02 and 04 against each."
            )

    try:
        paired = buffering_gap(args.paired)
        isolated = buffering_gap(args.isolated)
    except KeyError as exc:
        fail(str(exc))
        return 2

    common = sorted(set(paired.index) & set(isolated.index))
    if not common:
        fail("the two arms share no complexes, so nothing can be paired")
    if len(common) < len(paired) or len(common) < len(isolated):
        print(
            f"note: pairing on {len(common)} complex(es) present in both arms "
            f"(paired arm has {len(paired)}, isolated arm has {len(isolated)})",
            file=sys.stderr,
        )
    paired, isolated = paired.loc[common], isolated.loc[common]

    banner("09_partner_ablation", args, {"complexes": len(common)})

    with run_manifest(
        script=Path(__file__),
        parameters={
            "statistic": (
                "interface buffering ratio minus surface buffering ratio, "
                "differenced between arms and paired by complex"
            ),
            "arms": {
                "paired": "ProteinMPNN sees the whole complex",
                "isolated": "partner chain removed from the structure before featurisation",
            },
            "interface_definition_source": (
                "the native complex in both arms, so the two are compared over identical positions"
            ),
        },
        seeds={"seed": args.seed},
        inputs=[args.paired, args.isolated],
    ) as manifest:
        effect = paired_bootstrap_ci(isolated.tolist(), paired.tolist(), seed=args.seed)
        within_paired = bootstrap_ci(paired.tolist(), seed=args.seed)
        within_isolated = bootstrap_ci(isolated.tolist(), seed=args.seed)

        summary = {
            "n_complexes": len(common),
            "paired_arm": {
                "mean_interface_minus_surface": float(paired.mean()),
                "ci": [within_paired.low, within_paired.high],
                "excludes_zero": within_paired.excludes_zero,
                "n_buffering": int((paired < 0).sum()),
            },
            "isolated_arm": {
                "mean_interface_minus_surface": float(isolated.mean()),
                "ci": [within_isolated.low, within_isolated.high],
                "excludes_zero": within_isolated.excludes_zero,
                "n_buffering": int((isolated < 0).sum()),
            },
            "effect_of_removing_the_partner": {
                "estimate": effect.estimate,
                "ci": [effect.low, effect.high],
                "excludes_zero": effect.excludes_zero,
                "n_weakened": int((isolated > paired).sum()),
            },
            "conclusion": (
                "buffering depends on partner context"
                if effect.excludes_zero and effect.estimate > 0
                else "removing the partner did not measurably weaken buffering, so "
                "the effect is not attributable to partner context"
            ),
        }

        per_complex = pd.DataFrame(
            {
                "pdb_id": common,
                "gap_paired": paired.to_numpy(),
                "gap_isolated": isolated.to_numpy(),
                "weakened_without_partner": (isolated > paired).to_numpy(),
            }
        )
        table_path = results_dir / "partner_ablation.csv"
        summary_path = results_dir / "partner_ablation_summary.json"
        per_complex.to_csv(table_path, index=False)
        summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n")
        manifest.add_output(table_path)
        manifest.add_output(summary_path)
        manifest.note("n_complexes", len(common))
        manifest_target = manifest_path_for(table_path)

    manifest.write(manifest_target)

    print(f"\n=== partner ablation, {len(common)} complexes ===", file=sys.stderr)
    for label, block in (("partner present", "paired_arm"), ("partner removed", "isolated_arm")):
        entry = summary[block]
        print(
            f"  {label:<16} interface - surface = "
            f"{entry['mean_interface_minus_surface']:+.4f} "
            f"[{entry['ci'][0]:+.4f}, {entry['ci'][1]:+.4f}], "
            f"buffering in {entry['n_buffering']} of {len(common)}",
            file=sys.stderr,
        )
    effect_block = summary["effect_of_removing_the_partner"]
    print(
        f"\n  effect of removing the partner: {effect_block['estimate']:+.4f} "
        f"[{effect_block['ci'][0]:+.4f}, {effect_block['ci'][1]:+.4f}]  "
        f"{'RESOLVED' if effect_block['excludes_zero'] else 'includes zero'}",
        file=sys.stderr,
    )
    print(
        f"  weakened without the partner in {effect_block['n_weakened']} of {len(common)}",
        file=sys.stderr,
    )
    print(f"\n  {summary['conclusion']}", file=sys.stderr)
    print(f"\nmanifest hash: {manifest.manifest_hash}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
